cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #FRONT#
    path('add_to_cart/<int:id>', views.add_to_cart, name='add_to_cart'),
    path('order_summary/', views.order_details, name='order_summary'),
    path('success/', views.success, name='purchase_success'),
    path('item/delete/<int:id>', views.delete_from_cart, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    #BACK#
    path('all_orders/', views.all_orders, name='all_orders'),
    path('order/<int:id>', views.order_detail, name='order_detail'),
    path('order/delete/<int:id>', views.order_delete, name='order_delete')
]

mega/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import home_view
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from products import views

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('config/', include('config.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('allauth.urls')),
    path('home/', home_view, name='home'),
    path('', (TemplateView.as_view(template_name="admin/sw.js", content_type='application/javascript', extra_context={'name': 'caco'} )), name='sw.js'),
    path('manifest.json/', (TemplateView.as_view(template_name="admin/manifest.json", content_type='application/json', )), name='manifestjson'),
    path('install_sw/', (TemplateView.as_view(template_name="admin/install_sw.html", content_type='text/html', )), name='install_sw'),
    path('test_amp/', views.test_amp_view, name='test_amp'),
    path('test/', views.test_view, name='test'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from products.models import Produto, Estoque
from django.contrib.auth import get_user_model
from .managers import ItemManager
from django.core.exceptions import ValidationError
from .extras import generate_order_id


User = get_user_model()

class Pedido(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_ordered = models.DateTimeField(auto_now=True)


    @property
    def get_cart_total(self):
        total = 0
        for item in self.order_items.all():
            total_item = item.product.preco * item.quantity
            total += total_item
        return total

    def items(self):
        return Item.objects.filter(order=self)

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

    def save(self, *args, **kwargs):
        if not self.ref_code:
            self.ref_code = generate_order_id()
        super().save(*args, **kwargs)


class Item(models.Model):
    product = models.ForeignKey(Produto, on_delete=models.SET_NULL, null=True, related_name='product_items')
    order = models.ForeignKey(Pedido, on_delete=models.SET_NULL, null=True, related_name='order_items')
    size = models.ForeignKey(Estoque, on_delete=models.SET_NULL, null=True, related_name='storage')
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)
    quantity = models.PositiveIntegerField(default=1)
    objects = ItemManager()

    def __str__(self):
        return '{} -> {} '.format(self.product, self.order)

    def get_item_total(self):
        return self.product.preco * self.quantity


    def clean(self):
        if self.size != self.product.storage.filter(tamanho=self.size.tamanho).first():
            raise ValidationError('Estoque errado')

products/models.py
from django.db import models
from django.template.defaultfilters import slugify
from .managers import ProdutoManager, EstoqueManager
from phonenumber_field.modelfields import PhoneNumberField
from django.core.exceptions import ValidationError
from django.utils import timezone


class Tags(models.Model):
    tags = models.CharField(max_length=30)
    sub = models.BooleanField(default=False)

    def __str__(self):
            return '%s' % (self.tags)

    def clean(self):
        mod = Tags.objects.filter(tags=self.tags)
        if mod.exists():
            raise ValidationError('Tag Já Existe')
        
    def save(self, *args, **kwargs):
        self.tags = self.tags.capitalize()
        super().save(*args, **kwargs)


class SubTags(models.Model):
    tag = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)
    subtag = models.CharField(max_length=50)
    
    def save(self, *args, **kwargs):
        if self.tag.sub == False:
            t1 = Tags.objects.get(id=self.tag.id)
            t1.sub = True
            t1.save()
            super().save(*args, **kwargs)
        super().save(*args, **kwargs)


class Produto (models.Model):
    tag = models.ManyToManyField(Tags)
    nome = models.CharField(max_length=200)
    preco = models.DecimalField(max_digits=8, decimal_places=2)
    created_time = models.DateTimeField(auto_now=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    activate = models.BooleanField(default=True)

    objects = ProdutoManager()

    def __str__(self):
        return '%s - %s' % (self.nome, self.preco)
    
    def get_storage_total(self):
        total = 0
        e1 = self.storage.all()
        for e in e1:
            total += e.quantidade
        return total


    def all_buyed(self):
        total = 0
        for e in self.storage.all():
            total += e.quantidade
        for i in self.product_items.filter(is_ordered=True):
            total += i.quantity
        return total

    def all_selled(self):
        total = 0
        for i in self.product_items.filter(is_ordered=True):
            total += i.quantity
        return total

    def sell_percent(self):
        try:
            total = (self.all_selled() * 100)/ self.all_buyed()
            return total
        except ZeroDivisionError:
            return 'sem Vendidos'



class Estoque(models.Model):
    product = models.ForeignKey(Produto, on_delete=models.SET_NULL, null=True, related_name='storage')
    tamanho = models.CharField(max_length=100, null=True)
    quantidade = models.PositiveIntegerField(default=0)
    created_time = models.DateTimeField(auto_now=True)
    updated_time = models.DateTimeField(auto_now_add=True)
    objects = EstoqueManager()


    def __str__(self):
        return '%s - %s - %s' % (self.product,self.tamanho, self.quantidade)

    def clean(self):
        stor = Estoque.objects.filter(product=self.product, tamanho=self.tamanho)
        if stor.exists():
            raise ValidationError('Estoque já existente')
        
        

def get_image_filename(instance, filename):
    nome = instance.product.nome
    slug = slugify(nome)
    return "produto_imagens/%s-%s" % (slug, filename)


class Imagem (models.Model):
    product = models.ForeignKey(Produto, on_delete=models.SET_NULL, related_name='images', null=True)
    image = models.ImageField(upload_to=get_image_filename)


class Contact (models.Model):
    nome = models.CharField(max_length=100)
    phone = PhoneNumberField()
    email = models.EmailField()
    mensagem = models.TextField(max_length=600, default='Mensagem')

class Banner(models.Model):
    Inicial = 'Inicial'
    Mini = 'Mini'
    Adjacentes = 'Adjacentes'
    Promocao = 'Promocao'
    tipos_banner = [
        (Inicial, 'Inicial'),
        (Mini, 'Mini'),
        (Promocao, 'Promocao'),
        (Adjacentes, 'Adjacentes'),
    ]
    
    nome = models.CharField(max_length=100)
    tipo = models.CharField(max_length=10, choices=tipos_banner)

    def __str__(self):
        return '%s %s' % (self.nome, self.tipo)


def get_banner_image_filename(instance, filename):
    nome = instance.bannering.nome
    slug = slugify(nome)
    return "banner_imagens/%s-%s" % (slug, filename)

class BannerImages(models.Model):
    bannering = models.ForeignKey(Banner, on_delete=models.CASCADE, related_name='banner_image')
    imagem = models.ImageField(upload_to=get_banner_image_filename)
    link = models.URLField(max_length=200, default='products/home')

    def __str__(self):
        return '%s %s' % (self.bannering, self.imagem)

templates/admin_amp/Curriculo-mobile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curriculo Lucas Reimol</title>
</head>
<style>
    
    body{
        background-color: rgb(112, 96, 255);
        background-image: linear-gradient(to right, rgb(112, 96, 255), rgb(58, 37, 247));

    }

    div.page{
        margin-top: 0px;
        top: 0;
        background-color: white;
        max-width: 99%;
        padding-left: 0px;
        margin-left: 0;
        box-shadow: 4px 4px 4px 4px rgba(0, 0, 0, 0.2);
    }

    /*  HEADER  */



    div.header{
        margin-top: 20px;
        background-image: linear-gradient(to right, rgba(255, 255, 255, 0.5), rgba(168, 95, 0, 0.8));
        border-style: groove;
        border-color: blueviolet;
        margin-left: 0px;
        padding-left: 0px;
        height: inherit;
        float: left;
        position: fixed;
    }

    ul.header{
        margin-left: 0px;
        padding-left: 0px;
        margin-bottom: 20px ;
        height: inherit;
    }

    li.header{
        margin-left: 0px;
        padding-left: 0px;
        list-style: none;
    }

    a.header{
        text-decoration: none;
    }

    h1.header{
        color: white;
        text-shadow: 1px 1px rgb(0, 0, 0);
    }
    /* HEADER END */


    /* Profile */
    div.first{
        margin-top: 50px;
    }

    div.img{
        margin-top: 150px;
        height: 120px;
        width: 120px;
        border-style: groove;
        border-color: rgb(112, 96, 255);
    }

    div.nome{
        margin-left: 0px;
    }

    /* Profile END */

    /* TEXTS */
    .titling{
        color: rgba(190, 190, 190, 0.363);
        text-shadow: 2px 2px rgb(0, 0, 0);
    }



    /* COMPETENCIAS E EXPERIENCIAS */
    div.second{
    }

    div.exp{
        text-align: center;
        height: 80px;
        transition-property: height, display;
        transition-duration: 1s;
        z-index: 2;
        box-shadow: 4px 4px 4px 4px rgba(0, 0, 0, 0.2);
    }

    div.exp:hover{
        height: 900px;
        position: relative;
    }

    .disp-inline{

        margin-right: 70px;
    }

    div.exp2{
        z-index: -1;
        opacity: 0%;
        transition-property: opacity;
        transition-duration: 1s;
    }

    div.exp:hover > div.exp2{
        opacity: 100%;
        position: relative;
    }

    /* PROJETOS */
    div.exp-long{
        margin: 0;
        padding: 0;
        text-align: center;
        height: 50px;
        transition-property: height, display;
        transition-duration: 1s;
        box-shadow: 4px 4px 4px 4px rgba(0, 0, 0, 0.2);
    }

    div.exp-long:hover{
        height: 1300px;
        position: relative;
    }


    div.exp-long2{
        opacity: 0%;
        transition-property: opacity;
        transition-duration: 1s;
    }

    div.exp-long:hover > div.exp-long2{
        opacity: 100%;
        position: relative;
    }


    /* PROJETOS END */

    /* CERTIFICADOS */
    div.cert{
        box-shadow: 2px 2px 2px 2px rgba(0, 0, 0, 0.2);
        width: 99%;

    }

    /* CERTIFICADOS END */
    ul.list{
        text-align: left;

    }


    img.check1{
        border-color: red;
        border-style: dashed;
    }


    img.check2{
        border-style: dashed;
        border-color: blue;
    }

    img.check3{
        border-color: green;
        border-style: dashed;
    }

    div.whats{
    }

</style>
<body>
    <!-- <div class="header">
            <ul class="header">
                <li class="header">
                    <a class="header" href="">
                        <h1 class="header">Inicio</h1>
                    </a>
                </li>
                <li class="header">
                    <a class="header" href="">
                        <h1 class="header">Competências</h1>
                    </a>
                </li>
                <li class="header">
                    <a class="header" href="">
                        <h1 class="header">Experiências</h1>
                    </a>
                </li>
                <li class="header">
                    <a class="header" href="">
                        <h1 class="header">Contato</h1>
                    </a>
                </li>
            </ul>
        </div> -->
    <div class="page">
        <div class="first">
            <div class="img">
                <img src="https://media-exp1.licdn.com/dms/image/C4E03AQF7YTCNmJLtKw/profile-displayphoto-shrink_200_200/0?e=1603324800&v=beta&t=Bv_bT4xpxjlhX7mYGorvNXjPaQAyWiLjxK0NUcjj--c" width="120px" height="120px" alt="">
            </div>
            <div class="nome">
                <h1 class="tes titling">Lucas Reimol Faria</h1>
                <p>GitHub: <a href="https://github.com/lucasrf27">https://github.com/lucasrf27</a></p>
                <p>StackOverflow: <a href="https://stackoverflow.com/users/10493488/lucasrf27?tab=profile">https://stackoverflow.com/users/10493488/lucasrf27?tab=profile</a></p>
                <p>LinkedIn: <a href="https://www.linkedin.com/in/lucas-reimol-2439961a2/">https://www.linkedin.com/in/lucas-reimol-2439961a2/</a> </p>
                <i>"Quero jogar com os melhores."</i>
            </div>
        </div>
        <div class="second">
            <div class="exp">
                <h1 class="titling">Competências</h1>
                <div class="leg">
                    <span><img class="check1"> Iniciante</span>
                    <span><img class="check2"> Intermediário</span>
                    <span><img class="check3"> Avançado</span>
                </div>
                <div class="exp2 titling disp-inline">
                    <ul>
                        <h2>Front-end</h2>
                        <li>amp-html <img class="check3"></li>
                        <li>JavaScript <img class="check1"></li>
                        <li>Html <img class="check3"></li>
                        <li>CSS <img class="check3"></li>
                        <li>Analytics <img class="check2"></li>
                        <li>GoogleAds <img class="check1"></li>
                        <li>GIMP <img class="check2"></li>
                    </ul>
                    <ul>
                        <h2>Back-end</h2>
                        <li>Python <img class="check3"></li>
                        <li>Django <img class="check3"></li>
                        <li>django-rest-framework <img class="check2"></li>
                        <li>django-security <img class="check1"></li>
                        <li>Pytest <img class="check2"></li>
                        <li>Heroku <img class="check3"></li>
                        <li>GCloud <img class="check1"></li>
                        <li>SQLite <img class="check2"></li>
                        <li>PostgreSQL <img class="check1"></li>
                        <li>VirtualBox <img class="check2"></li>
                        <li>Git <img class="check2"></li>
                        <li>StackOverflow <img class="check3"></li>
                    </ul>
                    <ul>
                        <h2>Idiomas</h2>
                        <li>Ingles <img class="check3"></li>
                        <li>Espanhol <img class="check2"></li>
                    </ul>
                </div>
            </div>
            <div class="exp">
                <h1 class="titling">Experiências</h1>
                <div class="exp2">
                    <h2 class="titling">C2View</h2>
                    <a href="https://www.c2view.com.br">C2view.com.br</a>
                    <p>Atualmente de onde tiro minha renda. C2View é um MEI criado por mim e meu irmão <br>
                        buscando serviços para atender tanto a necessidade de um perfil online quanto <br>
                        a de gerênciamento portatil.
                    </p>
                    <li>Desenvolver sistema de gerenciamento e venda de produtos com base no django</li>
                    <li>Desenvolver e rastrear(amp-analytics) toda a plataforma online do cliente</li>
                    <p>Nota: Demais empresas fora do ramo de desenvolvimento de software em <a href="https://github.com/lucasrf27/Curriculo-Dev/tree/master/Curriculo-antigo"></a>https://github.com/lucasrf27/Curriculo-Dev/tree/master/Curriculo-antigo</p>
                </div>
            </div>
            <br>
            <div class="exp">
                <h1 class="titling">Projetos</h1>
                <div class="exp2">
                    <h2 class="titling">store_deployed</h2>
                    <p>E-commerce para empresa de roupas</p>
                    <a href="https://jrmoda.herokuapp.com/products/home">https://jrmoda.herokuapp.com/products/home</a><br>
                    <a href="https://github.com/lucasrf27/store_deployed">https://github.com/lucasrf27/store_deployed</a>
                    <div class="disp-inline">
                        <div>
                            <h4 class="titling">Front-end</h4>
                            <ul class="list">
                                <li> Front-end em amp-html, JavaScript e widgets</li>
                                <li> Versão mobile responsiva</li>
                                <li> Rastreio específico de tag por amp-analytics</li>
                            </ul>
                        </div>
                        <div>
                            <h4 class="titling"> Back-end</h4>
                            <ul class="list">
                                <li> Python, Django, PostgreSQL</li>
                                <li> Gerenciamento de Estoque, Vendas e Pedidos</li>
                                <li> Versão de operação para funcionarios</li>
                            </ul>
                        </div>
                    </div>
                    <h2 class="titling">PetLove</h2>
                    <p>Desafio</p>
                    <a href="https://github.com/petlove/vagas/blob/master/backend-ruby/README.md">https://github.com/petlove/vagas/blob/master/backend-ruby/README.md</a><br>
                    <a href="https://github.com/lucasrf27/Petlove">https://github.com/lucasrf27/Petlove</a>
                    <h2 class="titling">guiadeutilidades</h2>
                    <p>Site de comerciantes para revista local</p>
                    <a href="https://github.com/lucasrf27/guiadeutilidades">https://github.com/lucasrf27/guiadeutilidades</a>
                </div>
            </div>
            <div class="exp-long">
                <h1 class="titling">Certificados</h1>
                <div class="exp-long2">
                    <div class="cert">
                        <img src="https://raw.githubusercontent.com/lucasrf27/Curriculo-Dev/master/Curriculo-Dev/static/python-beyond-the-basics-1.jpg" width="200" height="200" alt="">
                        <h3 class="titling">Python Beyond the Basics</h3>
                        <p> Python beyond the basics vai profundo na nas utilizações de method e class, type de cada objeto, uso de iter, definição de __methods__ ex: __init__, tratamento de self, super. Brevemente sobre dashboards e bastante foco em decorators,  e inheritance.</p>
                    </div>
                    <div class="cert">
                        <img src="https://raw.githubusercontent.com/lucasrf27/Curriculo-Dev/master/Curriculo-Dev/static/python-managing-packages-1.jpg" width="200" height="200" alt="">
                        <h3 class="titling">Managing Python Packages and Virtual Environments.</h3>
                        <p>Curso de treinamento básico na parte de git, mas com mais foco em tratamento de VirtualEnvs</p>
                    </div>
                    <div class="cert">
                        <img src="https://raw.githubusercontent.com/lucasrf27/Curriculo-Dev/master/Curriculo-Dev/static/python-best-pratices-code-quality-1.jpg" width="200" height="200" alt="">
                        <h3 class="titling">Python best pratices code quality.</h3>
                        <p>Curso demostra melhores maneiras de ativar a doc daquele method ou classe, .help(), .__doc__, etc. e ferramentas para criar um bom ReadMe</p>
                    </div>
                    <div class="cert">
                        <h3 class="titling">Unit Testing with Python</h3>
                        <p>Curso focado no teste unitário, abrangendo a parte de unittest e Pytest.</p>
                        <p>Nota: Sem Certificado, pois minha licença estava para acabar e o final do curso era a respeito do Pytest, o qual ja havia aprendido, uso e prefiro.</p>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <div class="exp">
                <h1 class="titling">Contato</h1>
                <div class="exp2">
                    <p class="titling">(21) 9915-01586</p>
                    <div class="whats">
                        <p class="titling">(21) 9681-51502</p>
                        <a href="https://wa.me/5521968151502" target="_blank">
                            <img src="static/whats-icon.png" width="" height="50px" alt="">
                        </a>
                    </div>
                    <p class="titling">lucas.reimol@gmail.com</p>
                </div>
            </div>
        </div>

</body>

</html>

templates/admin_amp/admin.amp.html
{% extends "admin_amp/base.amp.html" %}
{% block title %}
  ADMIN
{% endblock %}
{% block content %}
    <div class="buttons">
        <div class="sub">
            <h3 class="filter-text center" >produtos</h3>
            <button class="main">
                <a class="main filter-text" href="{% url 'add_product' %}">  Adicionar Produto</a>
            </button>
            <button class="main">
                <a class="main filter-text" href="{% url 'all_products' %}"> Lista de Produtos</a>
            </button>
        </div>
        <div class="sub">
            <h3 class="filter-text center" >BANNERS</h3>
            <button class="main">
                <a class="main filter-text" href="{% url 'add_banner' %}"> Adicionar Banner</a>
            </button>
            <button class="main">
                <a class="main filter-text center" href="{% url 'add_banner' %}"> Lista de Banners</a>
            </button>
        </div>
        <div class="sub">
            <h3 class="filter-text center" >Pedidos</h3>
            <button class="main">
                <a class="main filter-text" href="{% url 'home_product' %}"> TODOS OS PEDIDOS</a>
            </button>
            <button class="main">
                <a class="main filter-text" href="{% url 'home_product' %}"> PEDIDOS PENDENTES</a>
            </button>
        </div>
        <div class="sub">
            <h3 class="filter-text center" >Contas</h3>
            <button class="main">
                <a class="main filter-text" href="{% url 'logout' %}"> logout</a>
            </button>
            <button class="main">
                <a class="main filter-text" href="{% url 'register' %}">Registrar</a>
            </button>
        </div>
    </div>

{% endblock %}

templates/admin_amp/automatic.amp.html
{% extends "admin_amp/base.amp.html" %}
{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">ALOW</button>
    </form>
{% endblock %}

templates/admin_amp/banner_add.amp.html
{% extends "admin_amp/base.amp.html" %}
{% block title %}
  ADD BANNER
{% endblock %}
{% block content %}

    <form id="banner-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        {{form2.as_table}}
        <input type="submit" name="submit" value="Submit " />
    </form>

{% endblock %}
</html>

templates/admin_amp/login.amp.html
 {% block title %} Login {% endblock title %} {% block content %}

<body>
    <h1>Login 1</h1>
    <form class="form-login" method="POST">
        {% csrf_token %}
        <label for="username">username:
            <input id="username" type="text" name="username" value="{{ username }}">
        </label><br>
        <label for="password">password:
            <input id="password" type="password" name="password" value="{{ password }}">
        </label> <br>
        <button type="submit">LOGIN</button>
    </form>
</body>
{% endblock %}

</html>

templates/admin_amp/modelo_add.amp.html
{% extends "admin_amp/base.amp.html" %}

{% block content %}
    
    <form method="POST" action-xhr="{% url 'add_modelo' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">ALOW</button>
    </form>

        
{% endblock %}

templates/admin_amp/produto_add.amp.html
{% extends "admin_amp/base.amp.html" %}
{% block content %}
    <form id="product-form" method='POST' action-xhr="{% url 'add_product' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{prod_form.as_p}}
        <input type="submit"/>
    </form>
{% endblock content %}

templates/admin_amp/signup.amp.html
{% extends "admin_amp/base.amp.html" %}

{% block content %}
    
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">ALOW</button>
    </form>

        
{% endblock %}

templates/admin_amp/update_product.amp.html
{% extends "admin_amp/base.amp.html" %}
{% block title %}Update Product {{prod.id}} {% endblock title %}
{% block content %}
{% load static %}
<body>
<div class="box-form">
    <h4 style="color: red;">{{model_form.errors}}</h4>
    <h4 style="color: red;">{{prod_form.errors}}</h4>
    <h4 style="color: red;">{{img_form.errors}}</h4>
    <h4 style="color: red;">{{storage_form.errors}}</h4>
    <h2 class="filter-text">{{prod}}</h2><br>
    <input name='table' type="radio" value="model_on" on='change:model-form.show, storage-form.hide, product-form.hide, img-form.hide, images.hide, storage-div.hide'>Criar Modelo
    <form id="model-form" method="POST" action-xhr="https://{{ request.META.HTTP_HOST }}{% url 'add_modelo' %}" hidden>
    <fieldset>
        {% csrf_token %}
        {{model_form.as_p}}
        {{model_form.errors}}
        <input type="submit"
        value="Subscribe" name="model">
    </fieldset>
    </form>

    <h2 class="filter-text"> Alterar Produto</h2>
    <input name='table' type="radio" value="img_on" on='change:product-form.show, storage-form.hide, model-form.hide, img-form.hide, images.hide, storage-div.hide'>Alterar produto
    <form id='product-form' method='POST' action-xhr="https://{{ request.META.HTTP_HOST }}{% url 'update_product' prod.id %}" hidden>
        <fieldset>
        {% csrf_token %}
        {{prod_form.as_p}}
        <input type="submit" name="producting">
        </fieldset>
    </form>


    <h2 class="filter-text">Imagem:</h2>
    <input name='table' type="radio" value="img_on" on='change:img-form.show, images.show, storage-form.hide,  model-form.hide, product-form.hide, storage-div.hide'>Adicionar img
    <form id="img-form" method='POST' action-xhr="https://{{ request.META.HTTP_HOST }}{% url 'update_product' prod.id %}" enctype="multipart/form-data" target="_top" hidden>
        <fieldset>
        {% csrf_token %}
            <label for="Image">
                {{img_form}}
            </label>
            <input type="submit" name="img">
        </fieldset>
    </form>

    <div id='images' hidden>
    {% for pic in prod.images.all %}
        <img src="{{pic.image.url}}" height="200px" width="200px" alt="">
        <a href="{% url 'delete_image' pic.id %}" data-balloon="remove this item from cart">
            <amp-img width="30" height="30" layout=fixed src="{% static 'icons/delete-icon2.png' %}" ></amp-img>
        </a>
    {% endfor %}
    </div>
    <br>
    <h2 class="filter-text">Estoques:</h2>
    <input name='table' type="radio" value="storage_on" on='change:storage-form.show, storage-div.show, model-form.hide,img-form.hide,product-form.hide,images.hide'>Adicionar estoque
    <div id="storage-div" hidden>
    {% for storage in prod.storage.all %}
        <h4 class="">Quantidade {{storage.quantidade}} Tamanho {{storage.tamanho}}</h4>
    {% endfor %}
    </div>
    <form id="storage-form" method="POST" action-xhr="https://{{ request.META.HTTP_HOST }}{% url 'update_product' prod.id %}" target="_top" hidden>
        <fieldset>
            {% csrf_token %}
            <p><label for="id_product">Product:</label> <select name="product" required id="id_product">
                  <option value="{{prod.id}}" selected>{{prod}}</option>
                </select></p>
                <p><label for="id_quantidade">Quantidade:</label> <input type="number" name="quantidade" value="0" min="0" required id="id_quantidade"></p>
                <p><label for="id_tamanho">Tamanho:</label> <select name="tamanho" required id="id_tamanho">
                  <option value="" selected>---------</option>
                  <optgroup label="Adulto">
                  <option value="P">P</option>
                  <option value="M">M</option>
                  <option value="G">G</option>
                  <option value="GG">GG</option>
                  </optgroup>
                  <optgroup label="Infantil">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  </optgroup>
                  <optgroup label="Calsa">
                  <option value="36">36</option>
                  <option value="38">38</option>
                  <option value="40">40</option>
                  <option value="42">42</option>
                  <option value="44">44</option>
                  <option value="46">46</option>
                  <option value="48">48</option>
                  <option value="50">50</option>
                  </optgroup>
                  <option value="unknown">Unknown</option>
                </select></p>
                <button type="submit" name="storage">Enviar</button>
                <h2>{{storage_form.errors}}</h2>
                <h2>{{storage_form.non_field_errors}}</h2>
        </fieldset>
    </form>
</div>
</body>


{% endblock %}